services:
  booking_database-service:
    image: postgres:16.0-alpine
    container_name: booking_database-container
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d booking_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      internal-network:

  booking_liquid-service:
    image: liquibase/liquibase
    container_name: booking_liquid-container
    depends_on:
      booking_database-service:
        condition: service_started
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${PG_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${PG_PASSWORD}
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://booking_database-container:5432/${PG_DATABASE}
      LIQUIBASE_LOG_LEVEL: WARNING
    volumes:
      - ./src/main/resources/db/changelog/:/liquibase/changelog
      - ./src/main/resources/db/db.changelog-master.xml:/liquibase/db.changelog-master.xml
    command: --changelog-file db.changelog-master.xml update
    networks:
      internal-network:

  booking-service:
    container_name: booking-service-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      booking_database-service:
        condition: service_healthy
    env_file: .env
    ports:
      - "${APP_PORT}:9014"
    networks:
      hls-lab-network:
        priority: 100
      internal-network:
        priority: 1000

networks:
  hls-lab-network: # Нужна для связи с другими сервисами проекта
    external: true
  internal-network: # Нужна исключительно для взаимодействия элементов внутри сервиса.
    external: true  # Костыль для реализации приоритетов назначения адресов сетевым интерфейсам
      # (параметр priority сейчас не работает - известный баг).
      # Адреса назначаются в алфавитном порядке названия сети, причем
    # internal и external сети сортируются отдельно. Поэтому пришлось
    # внутреннюю сеть обозначить как внешнюю.
    name: z-booking-internal-network

volumes:
  pg-data: